### ISSUE TITLE
Blend States Weirdness

### ISSUE THREAD

**Issue by catvvvveasel** [mrvux/dx11-vvvv#141] opened 2014-07-12 10:26 UTC
I've noticed a few times now that when first creating a shader, constant for example, it has a default blend state of blend not none on creation, on reloading the patch, it has blend state of none as it should. This isn't consistent, so doesn't do it always...

**Comment by mrvux** [comment] 2015-11-19 13:22
Ok since no news from this one, + no example to reproduce, closing.

**Closed by mrvux** 2015-11-19 13:22 UTC
